### ISSUE TITLE
Getting NullPointerException when using ashot in my project

### ISSUE THREAD

**Issue by yadavgabhi** [yandex-qatools/ashot#33] opened 2015-05-13 10:51 UTC
I am working on below code

               

		WebDriver wd = new FirefoxDriver();		
		wd.get("http://www.indiatimes.com");
		
		new AShot()
		  .shootingStrategy(new ViewportPastingStrategy(0))
		  .takeScreenshot(wd);

getting below error, please suggest the solution

Exception in thread "main" java.lang.NullPointerException
	at ru.yandex.qatools.ashot.screentaker.VerticalPastingShootingStrategy.shiftCoords(VerticalPastingShootingStrategy.java:90)
	at ru.yandex.qatools.ashot.screentaker.VerticalPastingShootingStrategy.getScreenshot(VerticalPastingShootingStrategy.java:43)
	at ru.yandex.qatools.ashot.screentaker.VerticalPastingShootingStrategy.getScreenshot(VerticalPastingShootingStrategy.java:33)
	at ru.yandex.qatools.ashot.screentaker.ScreenTaker.take(ScreenTaker.java:25)
	at ru.yandex.qatools.ashot.AShot.takeScreenshot(AShot.java:166)
	at ru.yandex.qatools.elementscompare.tests.MyTest.main(MyTest.java:28)

**Comment by pazone** [comment] 2015-05-13 12:25
Hello. Thank you for bug report. 
You don't really need in ViewportPastingStrategy with Firefox. This strategy used for browsers, that can not shoot whole page, for example, Android browser or some versions of Chrome. 
If you want to take screenshot of whole page in Firefox, use DefaultShootingStrategy:
```
Screenshot screenshot = new AShot()
                .takeScreenshot(wd);
```
Or if want to checkout ViewportPastingStrategy, just use viewport-shooting browser and take screenshot of some exact web element:

```
Screenshot screenshot = new AShot()
                .shootingStrategy(new ViewportPastingStrategy(0))
                .takeScreenshot(wd, someElement);
```

P.S. Your page has very big size. I recomend to enlarge your heap space.

**Comment by yadavgabhi** [comment] 2015-05-14 07:39
@pazone Thanks for your quick reply. Actually my requirement is to take whole page screenshot in Safari on Mac OS X. I tried AShot but not successful using same.

Below code used to take whole page screenshot :

    WebDriver wd = new SafariDriver();     
    wd.get("http://www.indiatimes.com");

    new AShot()
      .shootingStrategy(new ViewportPastingStrategy(0))
      .takeScreenshot(wd);

When using above code getting error which I mentioned earlier:
Exception in thread "main" java.lang.NullPointerException
at ru.yandex.qatools.ashot.screentaker.VerticalPastingShootingStrategy.shiftCoords(VerticalPastingShootingStrategy.java:90)
at ru.yandex.qatools.ashot.screentaker.VerticalPastingShootingStrategy.getScreenshot(VerticalPastingShootingStrategy.java:43)
at ru.yandex.qatools.ashot.screentaker.VerticalPastingShootingStrategy.getScreenshot(VerticalPastingShootingStrategy.java:33)
at ru.yandex.qatools.ashot.screentaker.ScreenTaker.take(ScreenTaker.java:25)
at ru.yandex.qatools.ashot.AShot.takeScreenshot(AShot.java:166)
at ru.yandex.qatools.elementscompare.tests.MyTest.main(MyTest.java:28)

Below code used to take specific element screenshot :

    WebDriver wd = new SafariDriver();     
    wd.get("http://www.indiatimes.com");
    WebElement we = wd.findElement(By.xpath("xpath for element"));
    new AShot()
      .shootingStrategy(new ViewportPastingStrategy(0))
      .takeScreenshot(wd, we);

When using above code it not taking screenshot in full length for mentioned element.

Please help me on same. or provide some code snippet to take whole page screenshot using AShot.
Thanks in advance.

**Comment by pazone** [comment] 2015-05-14 10:50
So you can use try example:
```
WebDriver wd = new SafariDriver();     
wd.get("http://www.indiatimes.com");
WebElement we = wd.findElement(By.cssSelector("body"));
new AShot()
  .shootingStrategy(new ViewportPastingStrategy(0))
  .takeScreenshot(wd, we);
```

Fix for the NPE will be released soon

**Comment by yadavgabhi** [comment] 2015-05-15 07:13
I tried your solution but it is not providing result as expected. FYI: I am using Mac OS X and Safari.

I also tried below code:
  ```java
WebDriver wd = new SafariDriver();     
wd.get("http://www.indiatimes.com");
WebElement we = wd.findElement(By.cssSelector("#hp_block_2"));
new AShot()
  .shootingStrategy(new ViewportPastingStrategy(0))
  .takeScreenshot(wd, we);
```
Again got unexpected result. Screenshot result is only half side of page from left. Please refer to "sf-test2.png".

![sf_test2](https://cloud.githubusercontent.com/assets/7882250/7648368/d52181b0-faff-11e4-8f13-f89719e84925.png)

Provide your inputs/suggestions for same.

**Comment by frolovs** [comment] 2015-05-15 12:24
@yadavgabhi, to capture screenshot on this site successfully:
 1. init ViewportPastingStrategy with 1.5 second scroll timeout - i.e. ViewportPastingStrategy(1500)
 2. wait some time for page to load
 3. hide header element

Please see code as well as screenshot bellow.

http://screenshot.net/6om5jtw.jpg

```java
public class IndiaTimes {
    public static void main(String[] args) throws IOException, InterruptedException {
        WebDriver wd = new SafariDriver();
        wd.get("http://www.indiatimes.com");
        Thread.sleep(5000);
        ((JavascriptExecutor) wd).executeScript("$('#wrap header').hide();");
        Thread.sleep(500);
        WebElement we = wd.findElement(By.cssSelector("#hp_block_2"));
        final Screenshot screenshot = new AShot()
                .shootingStrategy(new ViewportPastingStrategy(1500))
                .takeScreenshot(wd, we);
        final BufferedImage image = screenshot.getImage();
        ImageIO.write(image, "PNG", 
            new File(System.getProperty("user.home") + "/AShot_indiatimes.png"));
    }
}
```

**Comment by yadavgabhi** [comment] 2015-05-18 04:56
@frolovs I tried your code but still not able to achieve expected result. FYI: I am using Mac OS X and Safari. Please refer to below screenshot.

![sf_test2](https://cloud.githubusercontent.com/assets/7882250/7674552/3710edb2-fd48-11e4-8e0b-af5cc4e421b0.png)

**Comment by frolovs** [comment] 2015-05-18 06:59
@yadavgabhi, please provide software versions that you use. Also I see,that  it looks like  some images are not loaded completely, try to doble sleep timeouts. Also try to use latest vesrion of Safari and SafariDriver. FYI, I'm also using Mac OS X and Safari (latest versions).

**Comment by frolovs** [comment] 2015-05-18 07:26
@yadavgabhi, do you have a Retina display on your laptop?

**Comment by yadavgabhi** [comment] 2015-05-18 10:25
@frolovs Yes, I have Retina display. Safari version 8.0.3 (10600.3.18) and OSX Yosemite version 10.10.2.
Same code is working fine on windows OS for chrome.
Let me try to do some experiments. If need any more assistance will ask you. Thanks a lot for your help and time.

**Comment by frolovs** [comment] 2015-05-18 15:52
@yadavgabhi, the root cause for you are getting a half an image is that ViewportPastingStrategy is not yet supporting Retina displays - i.e. displays with devicePixelRatio > 1.

Do you really need to run tests on a device with a Retina display?

There are reasons for not to use Retina display when testing and the main reason is memory consumption - images from Retina display (DPR = 2) are four times larger than images with DPR=1

**Comment by yadavgabhi** [comment] 2015-05-19 05:46
@frolovs No it is not are required thing to run the tests on Reina display. I will try on my execution server. If need any assistance will ask from you guys.

Thanks a lot again for your help.

**Closed** 2015-05-20 14:35 UTC

**Comment by seekingKnowledge** [comment] 2016-07-14 16:15
public class IndiaTimes {
    public static void main(String[] args) throws IOException, InterruptedException {
        WebDriver wd = new SafariDriver();
        wd.get("http://www.indiatimes.com");
        Thread.sleep(5000);
        ((JavascriptExecutor) wd).executeScript("$('#wrap header').hide();");
        Thread.sleep(500);
        WebElement we = wd.findElement(By.cssSelector("#hp_block_2"));
        final Screenshot screenshot = new AShot()
                .shootingStrategy(new ViewportPastingStrategy(1500))
                .takeScreenshot(wd, we);
        final BufferedImage image = screenshot.getImage();
        ImageIO.write(image, "PNG", 
            new File(System.getProperty("user.home") + "/AShot_indiatimes.png"));
    }
}

@abhishekkyd @pazone @frolovs  I am using the code that you are suggesting that it will work for safari, but it is not working for me on safari... I have attached the screenshot I obtained using the code above... please provide any configuration i need for Safari and IE. 
I am new sorry if i ask some silly question or use inappropriate words...
thank you 
![image](https://cloud.githubusercontent.com/assets/20449387/16846920/5680e922-49e6-11e6-9b13-08356ea594ec.png)

**Comment by pazone** [comment] 2016-07-16 13:42
@seekingKnowledge just remove this: `.shootingStrategy(new ViewportPastingStrategy(1500))` . And it will work.
